[package]
name = "forest-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.forest-lib]
path = "../forest-lib"

[dependencies]
rand = "0.8.4"
